uploads = []

[[generated]]
id = "KO15hKCE4Yf1Mod5j29cy"
uri = "file://artifacts/barber-app/public/app-icon-source.png"
type = "image"
title = "barber app icon"

[[generated]]
id = "cMtjBgdXUjN0y9RHhPdxT"
uri = "file://artifacts/barber-mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "fgSO37L4okVN8NSR1gKtA"
uri = "file://artifacts/agenda-tv/assets/images/icon.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "MQCdn83BTyL_uSM11RYmt"
uri = "file://artifacts/agenda-tv/static-build/android/manifest.json"
type = "unspecified"
title = "Android Manifest (v1.0.16)"

[[outputs]]
id = "rcCQ8OTPqvVSJY4tJ0ldC"
uri = "file://artifacts/agenda-tv/eas.json"
type = "unspecified"
title = "EAS Config"

[[outputs]]
id = "fZwmwwHvRuNFNYHtgwmvS"
uri = "file://artifacts/barber-app/dist-electron/AgendaPlay-1.0.0-Linux.zip"
type = "unspecified"
title = "AgendaPlay 1.0.0 - Linux AppImage (zipped)"
